version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-sqlite-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/sqlite.db
    volumes:
      - sqlite-data:/app/data
    restart: unless-stopped

volumes:
  sqlite-data:
    driver: local
